services:

  configserver:
    image: leo7medina/configserver:latest
    mem_limit: 800m
    ports:
      - "8085:8085"
    networks:
      - leo-dev-network
    environment:
      SPRING_PROFILES_ACTIVE: git
      SPRING_APPLICATION_NAME: configserver

  eurekaserver:
    image: leo7medina/eurekaserver
    mem_limit: 800m
    ports:
      - "8065:8065"
    networks:
      - leo-dev-network
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_APPLICATION_NAME: eurekaserver
      EUREKA_HOSTNAME: eurekaserver

  hotels:
    image: leo7medina/hotels:latest
    mem_limit: 800m
    ports:
      - "8080:8080"
    networks:
      - leo-dev-network
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 800s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_APPLICATION_NAME: hotels
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8085/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8065/eureka/

  rooms:
    image: leo7medina/rooms:latest
    mem_limit: 800m
    ports:
      - "8081:8081"
    networks:
      - leo-dev-network
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 12s
        max_attempts: 3
        window: 800s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_APPLICATION_NAME: rooms
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8085/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8065/eureka/

  reservations:
    image: leo7medina/reservations:latest
    mem_limit: 800m
    ports:
      - "8082:8082"
    networks:
      - leo-dev-network
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 14s
        max_attempts: 3
        window: 1200s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_APPLICATION_NAME: reservations
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8085/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8065/eureka/

  gatewayserver:
    image: leo7medina/gatewayserver:latest
    mem_limit: 800m
    ports:
      - "8066:8066"
    networks:
      - leo-dev-network
    depends_on:
      - configserver
      - eurekaserver
      - hotels
      - rooms
      - reservations
    deploy:
      restart_policy:
        condition: on-failure
        delay: 50s
        max_attempts: 3
        window: 180s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_APPLICATION_NAME: gatewayserver
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8085/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8065/eureka/

networks:
  leo-dev-network:
    driver: bridge