services:
  hotels:
    image: leo7medina/hotels:latest
    mem_limit: 800m
    ports:
      - "8080:8080"
    networks:
      - leodev-network

  rooms:
    image: leo7medina/rooms:latest
    mem_limit: 800m
    ports:
      - "8081:8081"
    networks:
      - leodev-network

  reservations:
    image: leo7medina/reservations:latest
    mem_limit: 800m
    ports:
      - "8082:8082"
    networks:
      - leodev-network

networks:
  leodev-network: