spring:
  application:
    name: eurekaserver
  profile:
    active: default
#  config:
#    import: optional:configserver:http://localhost:8085/
    #uri: http://config-server:8085
server:
  port: 8065
#  servlet.context-path: /eureka
eureka:
  instance:
    hostname: ${EUREKA_HOSTNAME:localhost}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
#spring.application.name=eurekaserver
##spring.config.import=optional:configserver:http://localhost:8085/
#
#server.port=8065
#eureka.instance.hostname=localhost
#eureka.client.registerWithEureka=false
#eureka.client.fetchRegistry=false
#eureka.client.serviceUrl.defaultZone=http://localhost:8065/eureka/