spring:
  application:
    name: eureka-server
  profile:
    active: default
  config:
    import: optional:configserver:http://localhost:8085/
    uri: http://config-server:8085
#server:
#  port: 8065
#  servlet.context-path: /eureka
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

#spring.application.name=eurekaserver
##spring.config.import=optional:configserver:http://localhost:8085/
#
#server.port=8065
#eureka.instance.hostname=localhost
#eureka.client.registerWithEureka=false
#eureka.client.fetchRegistry=false
#eureka.client.serviceUrl.defaultZone=http://localhost:8065/eureka/