services:

  configserver:
    image: leo7medina/config-server:latest
    mem_limit: 800m
    ports:
      - 8085:8085
    networks:
      - leodev-network

  hotels:
    image: leo7medina/hotels:latest
    mem_limit: 800m
    ports:
      - "8080:8080"
    networks:
      - leodev-network
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 8s
        max_attempts: 3
        window: 800s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8085/

  rooms:
    image: leo7medina/rooms:latest
    mem_limit: 800m
    ports:
      - "8081:8081"
    networks:
      - leodev-network
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 1000s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8085/

  reservations:
    image: leo7medina/reservations:latest
    mem_limit: 800m
    ports:
      - "8082:8082"
    networks:
      - leodev-network
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 12s
        max_attempts: 3
        window: 1200s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8085/

networks:
  leodev-network: