services:

  config-server:
    image: leo7medina/config-server:latest
    mem_limit: 800m
    ports:
      - "8085:8085"
    networks:
      - leo-dev-network

  eureka-server:
    image: leo7medina/eureka-server
    mem_limit: 800m
    ports:
      - "8065:8065"
    networks:
      - leo-dev-network
    environment:
      EUREKA_HOSTNAME: eureka-server
      SPRING_PROFILES_ACTIVE: dev

  hotels:
    image: leo7medina/hotels:latest
    mem_limit: 800m
    ports:
      - "8080:8080"
    networks:
      - leo-dev-network
    depends_on:
      - config-server
      - eureka-server
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 800s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: optional:config-server:http://configserver:8085/
      CONFIG_SERVER: http://config-server:8085/
      EUREKA_SERVER: http://eureka-server:8065/eureka/

  rooms:
    image: leo7medina/rooms:latest
    mem_limit: 800m
    ports:
      - "8081:8081"
    networks:
      - leo-dev-network
    depends_on:
      - config-server
      - eureka-server
    deploy:
      restart_policy:
        condition: on-failure
        delay: 12s
        max_attempts: 3
        window: 1000s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: optional:config-server:http://configserver:8085/
      CONFIG_SERVER: http://config-server:8085/
      EUREKA_SERVER: http://eureka-server:8065/eureka/

  reservations:
    image: leo7medina/reservations:latest
    mem_limit: 800m
    ports:
      - "8082:8082"
    networks:
      - leo-dev-network
    depends_on:
      - config-server
      - eureka-server
    deploy:
      restart_policy:
        condition: on-failure
        delay: 14s
        max_attempts: 3
        window: 1200s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: optional:config-server:http://configserver:8085/
      CONFIG_SERVER: http://config-server:8085/
      EUREKA_SERVER: http://eureka-server:8065/eureka/

networks:
  leo-dev-network:
    driver: bridge